apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r0zmz8j13-nodejs 
  janus-idp.io/tekton: r0zmz8j13-nodejs
  backstage.io/kubernetes-id: r0zmz8j13-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r0zmz8j13-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml